version: '3.8'

services:
  db:
    image: postgres:18-alpine
    container_name: molten_db
    restart: always
    environment:
      POSTGRES_USER: molten_user
      POSTGRES_PASSWORD: molten_password
      POSTGRES_DB: molten_core
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: